### PR TITLE
Removed default internal access control

### PR DESCRIPTION
**Pull request by Jcurrie314**
I did not change everything to public because some did not feel like they needed to be accessible outside this scope

### CODE REVIEW

**Comment by hadiidbouk** [comment]
Thank you @Jcurrie314 , Well i have fix the `ChartProgressBar` class and forget about the `BarData` since i am not using a mac right now, so please edit this PR by removing the `ChartProgressBar` edits also all the edits outside the `classes/` directory because isn't necessary and like you mentioned in the issue it will be better if we import the `ChartProgressBar` pod.

**Review by hadiidbouk — CHANGES_REQUESTED** [review]
Thank you @Jcurrie314 , Well i have fix the ChartProgressBar class and forget about the BarData since i am not using a mac right now, so please edit this PR by removing the ChartProgressBar edits also all the edits outside the classes/ directory because isn't necessary and like you mentioned in the issue it will be better if we import the ChartProgressBar pod.

**Comment by Jcurrie314** [comment]
I'm not sure if that's what you meant. As I understand, you have fixed the permissions on your local machine and will merge them with this PR

**Review by hadiidbouk — COMMENTED** [review]
Sorry @Jcurrie314  i have fix the bug by myself, and like i told please wait for tomorow if you need to use the pod and for now you can copy the all the classes from `classes/` directory

**Pull request closed without merging**
